### ISSUE TITLE
ESPN sometimes enters wrong abbreviation, 

### ISSUE THREAD

**Issue by rsummers618** [rcfbanalysis/rcfbscraper#8]
http://espn.go.com/ncf/playbyplay?gameId=400548257&period=0

In oregon vs South Dakota, ESPN abbreviates oregon as EWU, This is incorrect.  I'm unsure how you are handling this. 

Perhaps we should replace it with the yard line of above and below abbreviation

**Comment by DylanEustice** [comment]
Yeah, I've noticed the same thing. It only happened about 7 or 8 times for all the games last year but it was still annoying. I had to go in and change it by hand.

**Comment by DylanEustice** [comment]
When parsing the data, if a abbreviation is used which it doesn't recognize, the parser will guess one of the two teams. Pressing 1 or 0 will confirm or deny that is the correct team. Pressing 2 will show the next candidate, as well as the previous line and the next line. If the abbreviation is completely wrong on ESPN's end (ie, showing SCAR in an Akron vs California game), the user can enter either the correct abbreviation, team name, or "t + 'team code'" and the parser will continue.
